### Get all patients
GET http://localhost:7071/api/vet/patients/
Accept: application/json

### Get patient by ID
GET http://localhost:7071/api/vet/patients/101
Accept: application/json

### Get all appointments
GET http://localhost:7071/api/vet/appointments/
Accept: application/json

### Get appointment by ID
GET http://localhost:7071/api/vet/appointments/1
Accept: application/json
